[__config__]
newver = "new_ver.json"
oldver = "old_ver.json"

[sing-box]
source = "github"
github = "SagerNet/sing-box"
use_latest_release = true
prefix = "v"

[sing-box-testing]
source = "github"
github = "SagerNet/sing-box"
use_max_tag = true
prefix = "v"
include_regex = '^v\d+.\d+.\d+(.*)?'
