# Generated by go2rpm 1.19.0

# https://github.com/caddyserver/xcaddy
%global goipath         github.com/caddyserver/xcaddy
Version:                0.4.6

%gometa -L -f

Name:           xcaddy
Release:        1%{?dist}
Summary:        Build Caddy with plugins

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

# Inject version string at build time so xcaddy reports the correct
# version instead of "(devel)" from debug.ReadBuildInfo().
# https://github.com/caddyserver/xcaddy/pull/262
Patch0:         0001-Support-setting-version-via-ldflags.patch

BuildRequires:  go-vendor-tools

Requires:       golang
Requires:       git-core

%description
Build Caddy with plugins.

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export LDFLAGS="-X %{goipath}/cmd.CustomVersion=v%{version}"
%gobuild -o %{gobuilddir}/bin/xcaddy %{goipath}/cmd/xcaddy

%install
%go_vendor_license_install -c %{S:2}
install -Dvm755 %{gobuilddir}/bin/xcaddy -t %{buildroot}%{_bindir}/

%{gobuilddir}/bin/xcaddy completion bash | \
    install -Dvm644 /dev/stdin %{buildroot}%{bash_completions_dir}/xcaddy
%{gobuilddir}/bin/xcaddy completion zsh | \
    install -Dvm644 /dev/stdin %{buildroot}%{zsh_completions_dir}/_xcaddy
%{gobuilddir}/bin/xcaddy completion fish | \
    install -Dvm644 /dev/stdin %{buildroot}%{fish_completions_dir}/xcaddy.fish

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/xcaddy
%{bash_completions_dir}/xcaddy
%{zsh_completions_dir}/_xcaddy
%{fish_completions_dir}/xcaddy.fish
