# Generated by go2rpm 1.19.0
%global goipath         github.com/zu1k/nali
%global gomodulesmode   GO111MODULE=on
Version:                0.8.1

%gometa -L -f

%global common_description %{expand:
An offline tool for querying IP geographic information and CDN provider.
一个查询IP地理信息和CDN服务提供商的离线终端工具.}

%global golicenses      LICENSE
%global godocs          README.md README_en.md

Name:           nali
Release:        1%{?dist}
Summary:        An offline tool for querying IP geographic information and CDN provider.

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
Source1:        %{archivename}-vendor.tar.bz2

%description %{common_description}

%prep
%autosetup -a1

%generate_buildrequires

%build
export GO_LDFLAGS="-X %{goipath}/internal/constant.Version=%{version}"

%gobuild -o %{gobuilddir}/bin/nali ./

%install
install -Dvm755 %{gobuilddir}/bin/nali -t %{buildroot}%{_bindir}/

%{gobuilddir}/bin/nali completion bash | \
    install -Dvm644 /dev/stdin %{buildroot}%{bash_completions_dir}/nali
%{gobuilddir}/bin/nali completion zsh | \
    install -Dvm644 /dev/stdin %{buildroot}%{zsh_completions_dir}/_nali
%{gobuilddir}/bin/nali completion fish | \
    install -Dvm644 /dev/stdin %{buildroot}%{fish_completions_dir}/nali.fish

%files
%license LICENSE
%doc README.md README_en.md
%{_bindir}/nali
%{bash_completions_dir}/nali
%{zsh_completions_dir}/_nali
%{fish_completions_dir}/nali.fish

%changelog
%autochangelog
