# Generated by go2rpm 1.19.0
%global goipath         github.com/natesales/q
%global gomodulesmode   GO111MODULE=on
Version:                0.19.12

%gometa -L -f

%global common_description %{expand:
A tiny command line DNS client with support for UDP, TCP, DoT, DoH, DoQ and
ODoH.}

%global golicenses      LICENSE transport/LICENSE
%global godocs          README.md

Name:           q
Release:        1%{?dist}
Summary:        A tiny command line DNS client with support for UDP, TCP, DoT, DoH, DoQ and ODoH

License:        Apache-2.0 AND GPL-3.0-only
URL:            %{gourl}
Source0:        %{gosource}
Source1:        %{archivename}-vendor.tar.bz2

BuildRequires:  go-rpm-macros

%description %{common_description}

%prep
%autosetup -a1

%generate_buildrequires

%build
export GO_LDFLAGS="-X main.version=%version -X main.date=$SOURCE_DATE_EPOCH"

%gobuild -o %{gobuilddir}/bin/q ./

%install
install -Dvm755 %{gobuilddir}/bin/q -t %{buildroot}%{_bindir}/

%files
%license LICENSE transport/LICENSE
%doc README.md
%{_bindir}/q
