# Generated by go2rpm 1.19.0
%global goipath         github.com/nxtrace/NTrace-core
%global gomodulesmode   GO111MODULE=on
Version:                1.7.0

%gometa -L -f

%global common_description %{expand:
Open source visual route tracking CLI tool.}

%global golicenses      LICENSE
%global godocs          AGENTS.md CLAUDE.md README.md README_zh_CN.md\\\
                        scripts/regression/README.md\\\
                        skills/nexttrace/SKILL.md\\\
                        skills/nexttrace/references/capability-matrix.md\\\
                        skills/nexttrace/references/cli-fallback.md\\\
                        skills/nexttrace/references/globalping.md\\\
                        skills/nexttrace/references/mcp-tools.md\\\
                        skills/nexttrace/references/output-templates.md\\\
                        skills/nexttrace/references/platform-notes.md\\\
                        skills/nexttrace/references/validation.md

Name:           nexttrace
Release:        1%{?dist}
Summary:        NextTrace, an open source visual route tracking CLI tool

License:        GPL-3.0-only
URL:            %{gourl}
Source0:        %{gosource}
Source1:        %{archivename}-vendor.tar.bz2

BuildRequires:  golang >= 1.26.1

%description %{common_description}

%prep
%autosetup -a1 -n NTrace-core-%{version}

%generate_buildrequires

%build
export GO_LDFLAGS="-X %{goipath}/config.Version=%{version} -X %{goipath}/config.BuildDate=$SOURCE_DATE_EPOCH"

%gobuild -o %{gobuilddir}/bin/nexttrace ./

%install
install -Dvm755 %{gobuilddir}/bin/nexttrace -t %{buildroot}%{_bindir}/

%files
%license LICENSE
%doc AGENTS.md CLAUDE.md README.md README_zh_CN.md scripts/regression/README.md
%doc skills/nexttrace/SKILL.md skills/nexttrace/references/capability-matrix.md
%doc skills/nexttrace/references/cli-fallback.md
%doc skills/nexttrace/references/globalping.md
%doc skills/nexttrace/references/mcp-tools.md
%doc skills/nexttrace/references/output-templates.md
%doc skills/nexttrace/references/platform-notes.md
%doc skills/nexttrace/references/validation.md
%{_bindir}/nexttrace

%changelog
%autochangelog
