# vmlinux: vmlinux filename format
vmlinux = "vmlinuz-{VERSION}"

# initrd: initrd filename format
initrd = "initramfs-{VERSION}.img"

# distro: distro name
distro = "Fedora"

# esp_mountpoint: defines where the EFI System Partition is located.
# Notice: no tailing /
esp_mountpoint = "/boot/efi"

# bootargs: your boot argument
[bootargs]
default = "rhgb quiet"
